# 修改读取文件的路径
# site_source: DIR

# 修改写入文件的路径
# site_destination: DIR

# 禁用自定义插件
# safe: BOOL

# 转换时排除的文件文件夹
exclude:
  - Gemfile
  - Gemfile.lock

# 转换时强制包含的文件文件夹
include: ["_pages"]

# 生成站点时保留选择的文件
# keep_files: [DIR]

# 设置时区
# timezone: TIMEZONE

# 设置文件的编码
# encoding: utf-8

title: Wangmmx Blog
name: Wangmmx's gitPages Blog
description: 
  gitPages+jekyll生成的页面，自定义了部分主题样式
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  Wangmmx

# jekyll-paginate configuration
paginate: 10

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate


permalink: /posts/:title/
excerpt_separator: <!--more-->
author: https://github.com/Wangmmx

host: 0.0.0.0

