# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'apham'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-91332049-1'

menu: 
  - name: 博客
    submenu:
      - name: 前端
        link: /projects/front-end
      - name: 后端
        link: /projects/back-end
      - name: JAVA
        link: /projects/java
      - name: NodeJS
        link: /projects/nodejs
      - name: 区块链
        link: /projects/blockchain
  - name: 个人主页
    link: /about-me
  - name: 标签
    link: /tags
  - name: 说说
    link: /moods
  - name: 高达
    link: /ganda
  - name: 猫奴
    link: /cats
  - name: 游戏
    submenu:
      - name: 动森
        link: /games/animal-crossing
      - name: 冒险岛
        link: /gemes/maple-story
  - name: 联系我
    submenu:
      - name: GitHub
        icon: github
        link: https://github.com/Wangmmx
      - name: CNDS
        icon: book
        link: https://blog.csdn.net/wangmmx725

    
