# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'apham'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-91332049-1'

menu: 
  - name: 博文目录
    submenu:
      - name: 技术
        link: /projects/microbam
      - name: 杂七杂八
        link: /projects/ourlegacy
  - name: 说说
    link: /
  - name: 标签
    link: /tags
  - name: 关于
    link: /about
  - name: 联系我
    submenu:
      - name: GitHub
        icon: github
        link: https://github.com/Wangmmx
      - name: CNDS
        icon: book
        link: https://blog.csdn.net/wangmmx725

    
